import assert from 'node:assert/strict';
import {AvatarPlayer} from '../static/player.js';
import {DisplayedMouth, mouthBounds, releaseAxis, samplePosition, compositeFace} from '../static/mouth.js';

globalThis.requestAnimationFrame = () => 1;
globalThis.cancelAnimationFrame = () => {};
const draws = [];
const canvas = {width:256,height:256,classList:{add(){}},getContext:()=>({drawImage:value=>draws.push(value)})};
const errors = [];
const player = new AvatarPlayer(canvas, {error:value=>errors.push(value)});
player.decodeMore = () => {};
const metadata = new TextEncoder().encode(JSON.stringify({kind:'idle',box:[0,0,1,1],affine:[1,0,0,0,1,0],blend:0,source_bounds:null,end_turn:0}));
const packet = new ArrayBuffer(44+1280+metadata.length+2);
const header = new DataView(packet);
[0x3256414e,0,0,0,0,640,1,0,metadata.length,0,1].forEach((value,i)=>header.setUint32(i*4,value,true));
new Uint8Array(packet,44+1280,metadata.length).set(metadata);
player.receive(packet);
assert.deepEqual(errors, [], 'NAV2 layered frames must be accepted');
assert.equal(player.decodeQueue.length, 1);
player.cancel(1);
player.now = player.audibleNow = () => 1;
const base = {close(){}};
player.scheduled.push({sequence:1,turn:1,when:0,bitmap:base,meta:{kind:'speech'}});
player.tick();
assert.ok(draws.includes(base), 'Cancellation still paints the current source video');
player.dispose();
console.log('NAV2 and cancellation presentation checks passed');

const face=new Uint8ClampedArray(256*256*4);
for(let i=0;i<face.length;i+=4)face.set([130,115,105,255],i);
for(let y=148;y<169;y++)for(let x=99;x<156;x++)face.set([190,35,50,255],(y*256+x)*4);
const bounds=mouthBounds(face);
assert.ok(bounds.every(Number.isFinite));
const source=[104,151,153,166];
const speech=(turn,faceRGB=face,sourceBounds=source)=>({turn,face:faceRGB,meta:{kind:'speech',blend:1,source_bounds:sourceBounds,end_turn:0}});
const end=turn=>({turn:0,meta:{kind:'end',blend:1,source_bounds:source,end_turn:turn}});
const mouth=new DisplayedMouth();
const first=mouth.display(speech(1),0);
assert.equal(first.blend,.2,'One actual paint, even after decode drops, advances alpha once');
const frozenWarp=[...first.warp];
const release=mouth.display(end(1),100);
assert.equal(release.face,face);
assert.equal(release.blend,.2,'Short utterance END retains actually displayed opacity');
assert.deepEqual(release.warp,frozenWarp,'First release uses the actually displayed warp');
assert.equal(release.shape,0);
mouth.committed('end',130);
assert.equal(mouth.display(end(1),230).shape,.5,'First slow paint does not consume visible release time');
assert.equal(mouth.display(end(1),330).blend,.2);
assert.equal(mouth.display(end(1),430).blend,.1);
assert.equal(mouth.display(end(1),530),null);
assert.equal(mouth.display(end(1),600),null,'Late END cannot restart completed release');
mouth.display(speech(2),700);mouth.cancel(2);
assert.equal(mouth.display(end(2),710),null);
assert.equal(mouth.display(speech(2),720),null);
assert.equal(mouth.display(speech(3),730).blend,.2,'A new utterance starts from source after cancellation');
assert.equal(mouth.display(end(2),740),null,'Old END must never replay previous RGB');
assert.equal(mouth.display(speech(3),750).blend,.4,'A cancelled old END cannot reset the newer displayed utterance');
const currentPlayer=new AvatarPlayer(canvas);
currentPlayer.mouth.display(speech(3),0);currentPlayer.lastBase={close(){}};
const beforeOldCancel=draws.length;
currentPlayer.cancel(1);
assert.equal(draws.length,beforeOldCancel,'Repeated cancellation of an older turn cannot erase the currently visible newer face');
currentPlayer.dispose();
assert.equal(draws.length,beforeOldCancel+1,'Disconnect restores the last source frame instead of leaving a generated mouth on screen');
const poses=new DisplayedMouth();
const original=poses.display(speech(1),0);
const moved=poses.display(speech(1,face,source.map((v,i)=>v+(i<2?3:1))),40);
assert.notDeepEqual(moved.warp,original.warp,'Stride-reused RGB follows the currently displayed source pose');
assert.equal(poses.display({turn:0,meta:{kind:'idle',blend:1,source_bounds:source,end_turn:0}},80).blend,.2);
assert.equal(poses.display({turn:0,meta:{kind:'idle',blend:1,source_bounds:source,end_turn:0}},120),null);
assert.equal(poses.display(speech(1),160).blend,.2,'A recovered gap resumes opacity from source');
let previous=-1;
for(let p=0;p<=255;p+=.25){const mapped=releaseAxis(p,153,166,147.5,168.5);assert.ok(mapped>=previous);previous=mapped;}
assert.equal(releaseAxis(0,153,166,147.5,168.5),0);
assert.equal(releaseAxis(255,153,166,147.5,168.5),255);
const released={warp:[1,1,0,0],shape:1,generated:[98.5,155.5,147.5,168.5],source:[104,151,153,166]};
assert.notEqual(samplePosition(128,190,released)[1],190,'Natural release warps the entire mouth map, beyond the speech ellipse');
const pixel={data:new Uint8ClampedArray([10,20,30,255])};
const paint={getImageData:()=>pixel,putImageData() {}};
compositeFace(paint,{meta:{box:[0,0,1,1],affine:[1,0,0,0,1,0]},mask:new Uint8ClampedArray([0,0,0,255])},{face,blend:1,warp:[1,1,0,0],shape:0});
assert.deepEqual([...pixel.data],[10,20,30,255],'A zero mask preserves the source pixel');
console.log('Actual display, short END, 200/200ms release, cancellation, new turn, gap, pose reuse and monotone sampling checks passed');
