import assert from 'node:assert/strict';
import {DisplayedMouth} from '../static/mouth.js';
const bitmap=()=>({closed:0,close(){this.closed++;}});
const speech=(turn,face)=>({turn,face,meta:{kind:'speech',end_turn:0}});
const end=turn=>({turn:0,meta:{kind:'end',end_turn:turn}});
const mouth=new DisplayedMouth(),first=bitmap(),next=bitmap();
const frame=speech(1,first);
assert.equal(mouth.display(frame,0).blend,.2);
assert.equal(frame.face,null,'The displayed mouth owns its bitmap');
assert.equal(mouth.display(speech(1,next),40).blend,.4);
assert.equal(first.closed,1);
assert.equal(mouth.display(end(1),100).blend,.4);
assert.equal(mouth.display(end(1),200).blend,.2);
assert.equal(mouth.display(end(1),300),null);
assert.equal(next.closed,1);
const second=bitmap();mouth.display(speech(2,second),400);mouth.cancel(2);
assert.equal(second.closed,1);assert.equal(mouth.display(end(2),450),null);
const third=bitmap();mouth.display(speech(3,third),500);mouth.cancel(1);
assert.equal(third.closed,0);assert.equal(mouth.turn,3);
mouth.clear();assert.equal(third.closed,1);
console.log('Simple mouth fade, cancellation, new turn and bitmap ownership passed.');

